name: 'XJ Checkin'
 
on:
  schedule:
    - cron: '1 16 * * *'
jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: 'Prepare Env'
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml
      - name: 'Run check in'
        run: |
          python main.py "${{ secrets.XJ_BASE_URL }}" "${{ secrets.XJ_EMAIL }}" "${{ secrets.XJ_PASSWORD }}" "${{ secrets.SJ_BASE_URL }}" "${{ secrets.SJ_TOKEN }}" "${{ secrets.SJ_REQUEST_SUFFIX }}"
